---
fixtures:
  repositories:
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core
    boolean: https://github.com/voxpupuli/puppet-boolean
    filemapper: https://github.com/voxpupuli/puppet-filemapper
    kmod: https://github.com/voxpupuli/puppet-kmod
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
